export const responseSettings = {
  notifications: {
    "#6131438": {
      "a_m.duration": "13.00",
      "a_s.image": "1297436_1728924207.gif",
      "a_m.position":
        '{"image":{"width":300,"height":300,"top":99,"left":250},"title":{"width":800,"height":121,"top":399,"left":0},"message":{"width":800,"height":80,"top":520,"left":0},"preset":null}',
      "a_m.min_sum": "150",
      "a_m.preset_position": "2",
      "alert.main": null,
      "a_m.font-family": "Open Sans",
      "a_m.title-template": "{name} - {sum}!",
      "a_m.background-color": "rgba(0,0,0,0)",
      "a_m.duration_type": "default",
      "a_m.target": null,
      "a_m.stand_alone": "0",
      "a_m.fixed-sum": "0",
      "a_m.show-float": "0",
      "a_m.names": null,
      "a_m.active": "1",
      "alert.text-style": null,
      "a_t-s.title": null,
      "a_t-s_title.font-size": "50",
      "a_t-s_title.font-weight": "normal",
      "a_t-s_title.font-style": "normal",
      "a_t-s_title.shadow-color": "rgba(0,0,0,0)",
      "a_t-s_title.shadow-width": "10",
      "a_t-s_title.animation": "none",
      "a_t-s_title.color": "rgba(153,153,153,1)",
      "alert.text-title.gradient-enabled": "0",
      "alert.text-title.gradient-color_1": "rgba(0,0,0,1)",
      "alert.text-title.gradient-color_2": "rgba(0,0,0,1)",
      "alert.text-title.gradient.deg": "0",
      "a_t-s.message": null,
      "a_t-s_message.font-size": "25",
      "a_t-s_message.font-style": "normal",
      "a_t-s_message.shadow-color": "rgba(0,0,0,0)",
      "a_t-s_message.shadow-width": "10",
      "a_t-s_message.animation": "none",
      "a_t-s_message.font-weight": "normal",
      "a_t-s_message.background-color": "rgba(0,0,0,0)",
      "a_t-s_message.color": "rgba(153,153,153,1)",
      "a_t-s_message.font-family": "Open Sans",
      "alert.text-message.gradient-enabled": "0",
      "alert.text-message.gradient-color_1": "rgba(0,0,0,1)",
      "alert.text-message.gradient-color_2": "rgba(0,0,0,1)",
      "alert.text-message.gradient.deg": "0",
      "alert.sound": null,
      "a_s.volume": "100",
      "a_s.speeker": "Maxim",
      "a_s.speed": "medium",
      "a_s.play": "1",
      "a_s.read-title": "0",
      "a_s.sound-file": null,
      "a_s.sound": "default.mp3",
      "a_s.voice-volume": "100",
      "alert.image": null,
      "a_s.image-file": null,
      "a_i.payment": "0",
      alert_animations: null,
      "a_a.show-animation": "none",
      "a_a.hide-animation": "none",
    },
  },
  followers: {
    "#6131385": {
      "s_more.type": "youtubeSubs",
      "subscribers.title-text": null,
      "s_t.template": "{name} подписался на вас",
      "s_t.color": "rgba(255,255,255,1)",
      "s_t.size": "50",
      "s_t.font-weight": "normal",
      "s_t.font-style": "normal",
      "s_t.shadow-color": "rgba(0,0,0,1)",
      "s_t.shadow-width": "1",
      "s_t.animation": "none",
      "s_t.background-color": "rgba(0,0,0,0)",
      "s_t.font-family": "Open Sans",
      "s_t.resub_template":
        "{name} подписался уже в {month} раз! Подписка уровня - {sub_plan}",
      "s_t.subgift_template":
        "{name_gifter} дарит подписку уровня {sub_plan} пользователю {name}",
      "subscribers.comment-text": null,
      "s_m.template": "{name} подписался на вас",
      "s_m.color": "rgba(255,255,255,1)",
      "s_m.size": "25",
      "s_m.font-weight": "normal",
      "s_m.font-style": "normal",
      "s_m.shadow-color": "rgba(0,0,0,1)",
      "s_m.shadow-width": "1",
      "s_m.animation": "none",
      "s_m.background-color": "rgba(0,0,0,0)",
      "s_m.font-family": "Open Sans",
      "s_m.resub_template": "{message}",
      "s_m.subgift_template": "",
      "subscribers.image": null,
      "s_i.image": "default.gif",
      "s_i.image-file": null,
      "subscribers.sound": null,
      "s_s.volume": "100",
      "s_s.sound": "default.mp3",
      "s_s.sound-file": null,
      "subscribers.more": null,
      "s_more.background-color": "rgba(0,0,0,0)",
      "s_more.duration": "8",
      "s_more.interval": "45",
      "s_more.visible": "1",
      "s_more.position":
        '{"all-text":{},"alert-message":{},"alert-image-wrap":{}}',
      "s_more.show_animation": "none",
      "s_more.hide_animation": "none",
      "s_more.min_viewers": "10",
    },
    "#6131386": {
      "s_more.type": "twitchFollowers",
      "subscribers.title-text": null,
      "s_t.template": "{name} подписался на вас",
      "s_t.color": "rgba(255,255,255,1)",
      "s_t.size": "50",
      "s_t.font-weight": "normal",
      "s_t.font-style": "normal",
      "s_t.shadow-color": "rgba(0,0,0,1)",
      "s_t.shadow-width": "1",
      "s_t.animation": "none",
      "s_t.background-color": "rgba(0,0,0,0)",
      "s_t.font-family": "Open Sans",
      "s_t.resub_template":
        "{name} подписался уже в {month} раз! Подписка уровня - {sub_plan}",
      "s_t.subgift_template":
        "{name_gifter} дарит подписку уровня {sub_plan} пользователю {name}",
      "subscribers.comment-text": null,
      "s_m.template": "{name} подписался на вас",
      "s_m.color": "rgba(255,255,255,1)",
      "s_m.size": "25",
      "s_m.font-weight": "normal",
      "s_m.font-style": "normal",
      "s_m.shadow-color": "rgba(0,0,0,1)",
      "s_m.shadow-width": "1",
      "s_m.animation": "none",
      "s_m.background-color": "rgba(0,0,0,0)",
      "s_m.font-family": "Open Sans",
      "s_m.resub_template": "{message}",
      "s_m.subgift_template": "",
      "subscribers.image": null,
      "s_i.image": "default.gif",
      "s_i.image-file": null,
      "subscribers.sound": null,
      "s_s.volume": "100",
      "s_s.sound": "default.mp3",
      "s_s.sound-file": null,
      "subscribers.more": null,
      "s_more.background-color": "rgba(0,0,0,0)",
      "s_more.duration": "8",
      "s_more.interval": "45",
      "s_more.visible": "1",
      "s_more.position":
        '{"all-text":{},"alert-message":{},"alert-image-wrap":{}}',
      "s_more.show_animation": "none",
      "s_more.hide_animation": "none",
      "s_more.min_viewers": "10",
    },
    "#6131387": {
      "s_more.type": "twitchHosts",
      "subscribers.title-text": null,
      "s_t.template": "{name} подписался на вас",
      "s_t.color": "rgba(255,255,255,1)",
      "s_t.size": "50",
      "s_t.font-weight": "normal",
      "s_t.font-style": "normal",
      "s_t.shadow-color": "rgba(0,0,0,1)",
      "s_t.shadow-width": "1",
      "s_t.animation": "none",
      "s_t.background-color": "rgba(0,0,0,0)",
      "s_t.font-family": "Open Sans",
      "s_t.resub_template":
        "{name} подписался уже в {month} раз! Подписка уровня - {sub_plan}",
      "s_t.subgift_template":
        "{name_gifter} дарит подписку уровня {sub_plan} пользователю {name}",
      "subscribers.comment-text": null,
      "s_m.template": "{name} подписался на вас",
      "s_m.color": "rgba(255,255,255,1)",
      "s_m.size": "25",
      "s_m.font-weight": "normal",
      "s_m.font-style": "normal",
      "s_m.shadow-color": "rgba(0,0,0,1)",
      "s_m.shadow-width": "1",
      "s_m.animation": "none",
      "s_m.background-color": "rgba(0,0,0,0)",
      "s_m.font-family": "Open Sans",
      "s_m.resub_template": "{message}",
      "s_m.subgift_template": "",
      "subscribers.image": null,
      "s_i.image": "default.gif",
      "s_i.image-file": null,
      "subscribers.sound": null,
      "s_s.volume": "100",
      "s_s.sound": "default.mp3",
      "s_s.sound-file": null,
      "subscribers.more": null,
      "s_more.background-color": "rgba(0,0,0,0)",
      "s_more.duration": "8",
      "s_more.interval": "45",
      "s_more.visible": "1",
      "s_more.position":
        '{"all-text":{},"alert-message":{},"alert-image-wrap":{}}',
      "s_more.show_animation": "none",
      "s_more.hide_animation": "none",
      "s_more.min_viewers": "10",
    },
    "#6131388": {
      "s_more.type": "twitchSubs",
      "subscribers.title-text": null,
      "s_t.template": "{name} подписался на вас",
      "s_t.color": "rgba(255,255,255,1)",
      "s_t.size": "50",
      "s_t.font-weight": "normal",
      "s_t.font-style": "normal",
      "s_t.shadow-color": "rgba(0,0,0,1)",
      "s_t.shadow-width": "1",
      "s_t.animation": "none",
      "s_t.background-color": "rgba(0,0,0,0)",
      "s_t.font-family": "Open Sans",
      "s_t.resub_template":
        "{name} подписался уже в {month} раз! Подписка уровня - {sub_plan}",
      "s_t.subgift_template":
        "{name_gifter} дарит подписку уровня {sub_plan} пользователю {name}",
      "subscribers.comment-text": null,
      "s_m.template": "{name} подписался на вас",
      "s_m.color": "rgba(255,255,255,1)",
      "s_m.size": "25",
      "s_m.font-weight": "normal",
      "s_m.font-style": "normal",
      "s_m.shadow-color": "rgba(0,0,0,1)",
      "s_m.shadow-width": "1",
      "s_m.animation": "none",
      "s_m.background-color": "rgba(0,0,0,0)",
      "s_m.font-family": "Open Sans",
      "s_m.resub_template": "{message}",
      "s_m.subgift_template": "",
      "subscribers.image": null,
      "s_i.image": "default.gif",
      "s_i.image-file": null,
      "subscribers.sound": null,
      "s_s.volume": "100",
      "s_s.sound": "default.mp3",
      "s_s.sound-file": null,
      "subscribers.more": null,
      "s_more.background-color": "rgba(0,0,0,0)",
      "s_more.duration": "8",
      "s_more.interval": "45",
      "s_more.visible": "1",
      "s_more.position":
        '{"all-text":{},"alert-message":{},"alert-image-wrap":{}}',
      "s_more.show_animation": "none",
      "s_more.hide_animation": "none",
      "s_more.min_viewers": "10",
    },
    "#6131389": {
      "s_more.type": "musicAlert",
      "subscribers.title-text": null,
      "s_t.template": "{name} подписался на вас",
      "s_t.color": "rgba(255,255,255,1)",
      "s_t.size": "50",
      "s_t.font-weight": "normal",
      "s_t.font-style": "normal",
      "s_t.shadow-color": "rgba(0,0,0,1)",
      "s_t.shadow-width": "1",
      "s_t.animation": "none",
      "s_t.background-color": "rgba(0,0,0,0)",
      "s_t.font-family": "Open Sans",
      "s_t.resub_template":
        "{name} подписался уже в {month} раз! Подписка уровня - {sub_plan}",
      "s_t.subgift_template":
        "{name_gifter} дарит подписку уровня {sub_plan} пользователю {name}",
      "subscribers.comment-text": null,
      "s_m.template": "{name} подписался на вас",
      "s_m.color": "rgba(255,255,255,1)",
      "s_m.size": "25",
      "s_m.font-weight": "normal",
      "s_m.font-style": "normal",
      "s_m.shadow-color": "rgba(0,0,0,1)",
      "s_m.shadow-width": "1",
      "s_m.animation": "none",
      "s_m.background-color": "rgba(0,0,0,0)",
      "s_m.font-family": "Open Sans",
      "s_m.resub_template": "{message}",
      "s_m.subgift_template": "",
      "subscribers.image": null,
      "s_i.image": "default.gif",
      "s_i.image-file": null,
      "subscribers.sound": null,
      "s_s.volume": "100",
      "s_s.sound": "default.mp3",
      "s_s.sound-file": null,
      "subscribers.more": null,
      "s_more.background-color": "rgba(0,0,0,0)",
      "s_more.duration": "8",
      "s_more.interval": "45",
      "s_more.visible": "1",
      "s_more.position":
        '{"all-text":{},"alert-message":{},"alert-image-wrap":{}}',
      "s_more.show_animation": "none",
      "s_more.hide_animation": "none",
      "s_more.min_viewers": "10",
    },
    "#6131390": {
      "s_more.type": "trovo_follower",
      "subscribers.title-text": null,
      "s_t.template": "{name} подписался на вас",
      "s_t.color": "rgba(255,255,255,1)",
      "s_t.size": "50",
      "s_t.font-weight": "normal",
      "s_t.font-style": "normal",
      "s_t.shadow-color": "rgba(0,0,0,1)",
      "s_t.shadow-width": "1",
      "s_t.animation": "none",
      "s_t.background-color": "rgba(0,0,0,0)",
      "s_t.font-family": "Open Sans",
      "s_t.resub_template":
        "{name} подписался уже в {month} раз! Подписка уровня - {sub_plan}",
      "s_t.subgift_template":
        "{name_gifter} дарит подписку уровня {sub_plan} пользователю {name}",
      "subscribers.comment-text": null,
      "s_m.template": "{name} подписался на вас",
      "s_m.color": "rgba(255,255,255,1)",
      "s_m.size": "25",
      "s_m.font-weight": "normal",
      "s_m.font-style": "normal",
      "s_m.shadow-color": "rgba(0,0,0,1)",
      "s_m.shadow-width": "1",
      "s_m.animation": "none",
      "s_m.background-color": "rgba(0,0,0,0)",
      "s_m.font-family": "Open Sans",
      "s_m.resub_template": "{message}",
      "s_m.subgift_template": "",
      "subscribers.image": null,
      "s_i.image": "default.gif",
      "s_i.image-file": null,
      "subscribers.sound": null,
      "s_s.volume": "100",
      "s_s.sound": "default.mp3",
      "s_s.sound-file": null,
      "subscribers.more": null,
      "s_more.background-color": "rgba(0,0,0,0)",
      "s_more.duration": "8",
      "s_more.interval": "45",
      "s_more.visible": "1",
      "s_more.position":
        '{"all-text":{},"alert-message":{},"alert-image-wrap":{}}',
      "s_more.show_animation": "none",
      "s_more.hide_animation": "none",
      "s_more.min_viewers": "10",
    },
    "#6131391": {
      "s_more.type": "trovo_subscriber",
      "subscribers.title-text": null,
      "s_t.template": "{name} подписался на вас",
      "s_t.color": "rgba(255,255,255,1)",
      "s_t.size": "50",
      "s_t.font-weight": "normal",
      "s_t.font-style": "normal",
      "s_t.shadow-color": "rgba(0,0,0,1)",
      "s_t.shadow-width": "1",
      "s_t.animation": "none",
      "s_t.background-color": "rgba(0,0,0,0)",
      "s_t.font-family": "Open Sans",
      "s_t.resub_template":
        "{name} подписался уже в {month} раз! Подписка уровня - {sub_plan}",
      "s_t.subgift_template":
        "{name_gifter} дарит подписку уровня {sub_plan} пользователю {name}",
      "subscribers.comment-text": null,
      "s_m.template": "{name} подписался на вас",
      "s_m.color": "rgba(255,255,255,1)",
      "s_m.size": "25",
      "s_m.font-weight": "normal",
      "s_m.font-style": "normal",
      "s_m.shadow-color": "rgba(0,0,0,1)",
      "s_m.shadow-width": "1",
      "s_m.animation": "none",
      "s_m.background-color": "rgba(0,0,0,0)",
      "s_m.font-family": "Open Sans",
      "s_m.resub_template": "{message}",
      "s_m.subgift_template": "",
      "subscribers.image": null,
      "s_i.image": "default.gif",
      "s_i.image-file": null,
      "subscribers.sound": null,
      "s_s.volume": "100",
      "s_s.sound": "default.mp3",
      "s_s.sound-file": null,
      "subscribers.more": null,
      "s_more.background-color": "rgba(0,0,0,0)",
      "s_more.duration": "8",
      "s_more.interval": "45",
      "s_more.visible": "1",
      "s_more.position":
        '{"all-text":{},"alert-message":{},"alert-image-wrap":{}}',
      "s_more.show_animation": "none",
      "s_more.hide_animation": "none",
      "s_more.min_viewers": "10",
    },
  },
  system: {
    "alert-box.main": null,
    "a-b_m.show_notifications": "1",
    "a-b_m.show_followers": "0",
    "a-b_m.show_media": "0",
    "a-b_m.show_voter": "0",
    "a-b_m.moderation_enabled": "0",
    "a-b_m.moderation_skip_time": "0",
    "a-b_m.moderation_skip_amount": "0",
    "a-b_m.audio_enabled": "0",
    "a-b_m.audio_max_time": "30",
    "a-b_m.audio_min_amount": "100",
    "a-b_m.video_enabled": "0",
    "a-b_m.video_max_time": "30",
    "a-b_m.video_min_amount": "100",
    mainVolume: "100",
  },
  media: {
    "media.main": null,
    "m_m.enabled": "0",
    "m_m.min-sum": "0",
    "m_m.background-color": "rgba(0,0,0,0)",
    "m_m.auto-play": "1",
    "m_m.volume": "100",
    "m_m.tariff": "2",
    "m_m.tariff-sum": "0",
    "m_m.min-like-percent": "50",
    "m_m.min-view-count": "50000",
  },
  donation: {
    notification_type: "by_sum",
  },
};
